# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ramen Map' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ramen-Map
  pod 'HCSStarRatingView', '~> 1.5'
  pod 'QuadratTouch', :git => 'https://github.com/Constantine-Fry/das-quadrat', :branch => 'fry-swift30'

end